# Generated by Django 4.1.3 on 2022-11-04 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Directors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "types",
                    models.CharField(
                        choices=[("D", "director"), ("W", "writer"), ("A", "actor")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=5000)),
                ("poster", models.FileField(upload_to="poster/")),
                ("bg_picture", models.FileField(upload_to="bg_picture/")),
                ("release_year", models.PositiveSmallIntegerField()),
                (
                    "mpa_rating",
                    models.CharField(
                        choices=[
                            ("G", "General Audiences"),
                            ("PG", "Parental Guidance"),
                            ("PG-13", "Parents Strongly Cautioned"),
                            ("R", "Restricted"),
                            ("NC-17", "Adults Only"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "imdb_rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("duration", models.IntegerField()),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movie_directors", to="cinema_app.person"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        null=True, related_name="movie_genres", to="cinema_app.genre"
                    ),
                ),
                (
                    "stars",
                    models.ManyToManyField(
                        null=True, related_name="movie_stars", to="cinema_app.person"
                    ),
                ),
                (
                    "writers",
                    models.ManyToManyField(
                        related_name="movie_writers", to="cinema_app.person"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
